### ISSUE TITLE
Mark all as read broken?

### ISSUE THREAD

**Issue by tsdryden** [soufianesakhi/feedly-filtering-and-sorting#52]
The Chrome extension seems to break the "Mark All as Read" button at the bottom of the article list. When I click it either nothing happens, or it just shows me the same list of articles I just saw.

**Comment by soufianesakhi** [comment]
Did you try with the extension disabled ?

**Comment by tsdryden** [comment]
I did try disabling the extension and refreshing the page. It works as usual then.

**Comment by soufianesakhi** [comment]
Do you have any of the "Recently received articles" advanced options enabled?
Else can you export your settings, remove the keywords (if you want to) and send them to me so I can try to reproduce the problem?

**Comment by soufianesakhi** [comment]
Does the problem occur by any chance only on the 'latest' page ?

**Comment by soufianesakhi** [comment]
I have released the 3.12.3 version, can you test it and confirm that your problem is fixed ?

**Comment by tsdryden** [comment]
That doesn’t seem to have fixed the problem. When I go through my feeds group by group the Mark All as Read seems to work, but when I get done with all of them the Today group pops up with all of the articles I thought had been deleted still showing up! And no matter how many times I click the Mark All as Read button at the bottom of that list the articles won’t go away. Once I disable the extension and refresh the page, the Mark All as Read button works like it should.

**Comment by soufianesakhi** [comment]
Do you have any of the "Recently received articles" advanced options enabled?

**Comment by tsdryden** [comment]
Just “Kept unread if unread”.
But if I mark them as read, then they’re no longer “unread” and shouldn’t be kept, right?

Oh, and that option should should say “Keep”, not “Kept”.

**Comment by soufianesakhi** [comment]
The options read as follows:

Articles received (crawled) less than x hours and y days ago should be:
- Kept unread if unread
- Hidden
- Visible if hot or popularity superior to: z
- Marked as read if hot or popular  

If the first option is enabled, no article received (crawled) less than x hours and y days ago will be marked as read.
It's helpful when you want to wait for new article to become "more" popular so they get sorted later by popularity.

**Comment by tsdryden** [comment]
I’m not sure I understand that, but does that mean I shouldn’t use that option?

I’ve never cared about popularity anyway, so that’s probably why I didn’t get it. I read the article if it looks interesting to me, I don’t give a damned whether it’s popular or not. I guess some people care more about that stuff than I do.

**Comment by tsdryden** [comment]
It looks like unchecking that option did the trick. Thanks!

**Comment by tsdryden** [comment]
It’s working fine now. Thanks for your help!

**Comment by soufianesakhi** [comment]
You're welcome :)
