### ISSUE TITLE
Empty blocks

### ISSUE THREAD

**Issue by Detsle** [soufianesakhi/feedly-filtering-and-sorting#95]
I noticed that at times there are empty blocks, I cannot trace the pattern yet.

Screenshot:
![image](https://user-images.githubusercontent.com/22348086/115011511-5f4cbb00-9eb7-11eb-8310-498be831e575.png)

**Comment by soufianesakhi** [comment]
Fixed in v3.20.1. Let me know if it's not working as expected

**Comment by Detsle** [comment]
![app](https://user-images.githubusercontent.com/22348086/117978502-9e492180-b33a-11eb-8014-b89ccc2d559c.png)
![feedly](https://user-images.githubusercontent.com/22348086/117978578-b3be4b80-b33a-11eb-89e0-2f4e8cc05584.png)
Good afternoon, the extension has been updated, but the problem remains.

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by Detsle** [comment]
All perfectly!

**Comment by soufianesakhi** [comment]
Can you export your settings using the extension and send it to soufiane.sakhi.ks@gmail.com ?

**Comment by Detsle** [comment]
I noticed voids from about 150 blocks.
The export of the settings was sent to the mail.
